---
- name: Enable backports repository
  apt_repository:
    repo: deb http://ftp.debian.org/debian jessie-backports main
    state: present

- name: update the apt cache
  apt: update_cache=yes cache_valid_time=7200

- name: Install nginx
  apt:
    name: nginx
    state: latest
    default_release: jessie-backports
